### ISSUE TITLE
Ilia Repin -> Ilya Repin

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/vsevolod-garshin_short-fiction_rowland-smith#2]
Can you update the spelling both in metadata and colophon? We already have a few works with him as the artists so we want to be consistent.

**Comment by robinwhittleton** [comment]
Fixed (https://github.com/robinwhittleton/vsevolod-garshin_short-fiction_rowland-smith/commit/144540f5afc1b7be898f573030384f08c1508627) in the colophon; looks like I got it right in the metadata.
