### ISSUE TITLE
local.css issues

### ISSUE THREAD

**Issue by acabal** [robinwhittleton/vsevolod-garshin_short-fiction_rowland-smith#4]
- Missing footer styling: `footer{ margin-top: 1em; text-align: right; }`
- First lines of letters after salutation should have `text-indent: 0;`; for example in `an-incident.xhtml`

**Comment by robinwhittleton** [comment]
Fixed in https://github.com/robinwhittleton/vsevolod-garshin_short-fiction_rowland-smith/commit/1777dc76e585393d349354a2665f88d53377b534. I amended the letter markup to include the missing `salutation` too.
